const ScreenNames = {
  LANDING: 'LANDING',
  LOGIN: 'Login',
  HOME: 'Home',
  SignInScreen: 'SignInScreen',
  PhoneNumberScreen: 'PhoneNumberScreen',
  CodeScreen: 'CodeScreen',
  EmailScreen: 'EmailScreen',
  WelcomeScreen: 'WelcomeScreen',
  NameScreen: 'NameScreen',
  BirthdayScreen: 'BirthdayScreen',
  GenderScreen: 'GenderScreen',
  SexualOrientationScreen: 'SexualOrientationScreen',
  MatchesScreen: 'MatchesScreen',
  UnderDevelopmentScreen: 'UnderDevelopmentScreen',
  ChatListScreen: 'ChatListScreen',
  ChatScreen: 'ChatScreen',
  StarScreen: 'StarScreen',
  ProfileScreen: 'ProfileScreen',
  BenefitsScreen: 'BenefitsScreen',
  EditProfileScreen: 'EditProfileScreen',
  ProfesionScreen: 'ProfesionScreen',
  AppointmentPreferenceScreen: 'AppointmentPreferenceScreen',
  ProfessionalStaticScreen: 'ProfessionalStaticScreen',
  AgePreferenceScreen: 'AgePreferenceScreen',
  AgePreferenceScreenNonStatic: 'AgePreferenceScreenNonStatic',
  InterestsScreen: 'InterestsScreen',
  ShowmeScreen: 'ShowmeScreen',
  AddPhotosScreen: 'AddPhotosScreen',
  UserProfileScreen: 'UserProfileScreen',
  ConfigurationScreen: 'ConfigurationScreen',
  ConnectedAccountsScreen: 'ConnectedAccountsScreen',
  EmailVerificationScreen: 'EmailVerificationScreen',
  NameEditScreen: 'NameEditScreen',
  VerificationScreen: 'VerificationScreen',
  BlockedContactsScreen: 'BlockedContactsScreen',

  HomeStack: 'HomeStack',
  LikeStack: 'LikeStack',
  ChatStack: 'ChatStack',
  ProfileStack: 'ProfileStack',
};
export default ScreenNames;
